### ISSUE TITLE
[BUG 🐞] Change Heading Styles for Dark Mode

### ISSUE THREAD

**Issue by warmachine028** [warmachine028/nike#55]
### Description

- The Heading style doesn't look great in Dark theme in Hero Section.
- Please add a better style for it to enhance the beauty of the page.

### Screenshots
<div align="center">
    <img src="https://github.com/warmachine028/nike/assets/75939390/fb36df07-c6d4-4eec-b4b8-ec513c7bba7b" width="300"/>
</div>

<div align="center">
    <img src="https://github.com/warmachine028/nike/assets/75939390/b362374c-e64e-4d73-ac69-758a410ca105" width="700"/>
</div>

## Happy contributing. 💐
Star my other Repositories [here](https://github.com/warmachine028)

**Comment by warmachine028** [comment]
As you can see, the background of the Heading text looks very unmatched to the overall site aesthetics only for Dark Mode. Do something to make it look better.

**Comment by Sky-De** [comment]
@warmachine028 check this out , if it is ok with you let me know to make PR

## SCREENSHOTS

**Desktop**
![d-d](https://github.com/warmachine028/nike/assets/79264045/2f723f89-48e8-43f1-aee7-70ef9f8594cb)
![d-l](https://github.com/warmachine028/nike/assets/79264045/87758839-5bf4-4a20-ac23-9aa9f2c4181f)

**Mobile**
![m-d](https://github.com/warmachine028/nike/assets/79264045/f504f1c9-d3b1-4eab-9de3-a7eca130069e)
![m-l](https://github.com/warmachine028/nike/assets/79264045/4004e357-2196-4fa2-b9ab-c8070287af9b)

**Comment by warmachine028** [comment]
Looks much better, also could you match the h1 text for the dark theme, that grey background in the text doesn't quite match the overall aesthetics of the site

**Comment by Sky-De** [comment]
@warmachine028 i removed that gray bg from mobile dark/light and desktop light mode but i kept that in desktop dark mode because of this : 
![deskt](https://github.com/warmachine028/nike/assets/79264045/560300f4-469a-4d0a-8520-103112a2fa75)

## Final screenshots

**Desktop**

![dark-d](https://github.com/warmachine028/nike/assets/79264045/2cc183a3-23d9-47d0-99bf-67e100b42510)

![light-d](https://github.com/warmachine028/nike/assets/79264045/fd6477b0-ff59-4aae-9260-e95d753d8308)



**Mobile**

![light-m](https://github.com/warmachine028/nike/assets/79264045/0c6b9e1c-c5c4-4d73-afef-8760fa2ac5aa)
![dark-m](https://github.com/warmachine028/nike/assets/79264045/2662b536-9d4b-4830-acc3-5066a24ad45a)

if you got any question feel free to ask, otherwise let me know to send PR
thanks

**Comment by warmachine028** [comment]
Yes looks perfect now

**Comment by warmachine028** [comment]
Make a PR, I'll merge it
